### ISSUE TITLE
Doesn't work with IE8

### ISSUE THREAD

**Issue by fxcoudert** [jwilsson/AnySlider#21]
I've got a setup close to that of the documentation (see it live: http://coudert.name/). It behaves well with IE > 8, Chrome, FF and Safari. But it's broken with IE8:

![sa29906_windows_7__ie_8 0 png](https://cloud.githubusercontent.com/assets/1980544/7671257/9a08c434-fcc7-11e4-9789-1656c638dfd8.jpeg)

The doc says "Supported in all major browsers", and as IE8 is the 2nd browser in terms of market shares (after IE11), I guess it's a "major browser".

**Comment by jwilsson** [comment]
Hi,
I think the problem lies with the site using jQuery 2.x which doesn't support IE8. If it's possible, try using jQuery 1.x and see if that solves the problem.

Otherwise, it could be a bug with AnySlider.

**Comment by fxcoudert** [comment]
True! I had just followed the doc. I confirm that, with jQuery 1.x, it works on IE8 (and doesn't break on other browsers). Thanks!
