### ISSUE TITLE
Vertical scrolling problem on mobile devices and tablets

### ISSUE THREAD

**Issue by davidsancho** [jwilsson/AnySlider#22]
I want to slide (rigth - left) a big in height  div but I need also doing vertical scrolling.
When I try to do vertical scrolling on mobile devices my div slides to the next one 
Any Solution 
Thanks a lot and sorry for my bad English

**Comment by jwilsson** [comment]
Hi,
Vertical scrolling should work on iOS, Android and Windows Phone. Which device(s) are you seeing this on? Could you provide the OS version as well?

Thanks!

**Comment by davidsancho** [comment]
I have solved changing this line in anyslider.js
if (startTime !== 0 && currentTime - startTime < 1000 && currentDistance > 10) {
for               
  if (startTime !== 0 && currentTime - startTime < 1000 && currentDistance > 200) {

it seems to be the precision of the horizontal slide.

**Comment by jwilsson** [comment]
Great! You wanna submit a pull request for it?
