### ISSUE TITLE
active bullet and Controls errors

### ISSUE THREAD

**Issue by PhpMax** [jwilsson/AnySlider#23]
Hello,
I see all bullets are blue, Active bullet class .as-active is working I tried to add (border-top:1px solid #000000;) active bullet should be light blue not blue. I don't see the light bullet.

Another problem: When I use 
            animation: 'fade',
            showControls: true,

There will be problem in clicking on the arrows on the slider sides.
Is there a solution for both problems. Browser FF 38
Thanks,

**Comment by jwilsson** [comment]
Hi!
Yeah, there seems to be two CSS issues in the demo code. They should be easy fixable for now like this:

The `.as-active` class has a lower specificity than `.as-nav a`, so just make sure `.as-active` has a higher one, for example:
```
.as-nav .as-active {
    /* Active styles... */
}
```

The other issue with arrow and fading slides seems to be `z-index` related, increase `z-index` on the arrows like this to fix it:
```
.as-prev-arrow,
.as-next-arrow {
    z-index: 2;
}
```

That should do the trick and I'll make sure to update the demo CSS so it's working in the future.

**Comment by PhpMax** [comment]
Thanks, 
problems solved.
Best regards
