### ISSUE TITLE
Unable to call 'next()' method

### ISSUE THREAD

**Issue by JamesNock** [jwilsson/AnySlider#24]
Hi guys, firstly... nice plugin; really like it!

I'm not sure if this is an issue or just me being thick but I have a slider initiated using the following code:

`$('.slider').anyslider({
        easing: 'linear',
        interval: 0,
        keyboard: false,
        speed: 300,
        keyboard:false,
        showControls:false
    });`

I'm trying to use the 'next' function like so:

`$('.js-next').on('click',function(){
            $('.slider').anyslider().next();
    });`

But this doesn't work. I've tried adding a console.log inside the next function and it doesn't appear in my console either so I'm convinced that the method isn't firing. Do you have any ideas?

**Comment by jwilsson** [comment]
Hi,
You need to fetch the AnySlider instance from the slider element first, so your `next` call will look something like this:

```
$('.slider').data('anyslider').next();
```

Hope that solves it!

**Comment by JamesNock** [comment]
Brilliant, problem solved. I wonder whether it might be useful to mention that in the README. Thank you!
